<a href="https://colab.research.google.com/github/data-prom/Kaggle_daily_commit/blob/master/torch_tutorial/Playground.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# 파이썬 2에서 파이썬 3로 넘어갈 수 있게끔 도와주는 라이브러리 __future__
from __future__ import print_function
import torch

In [2]:
# 초기화되지 않은 행렬 생성되면 할당된 메모리에 존재하던 값이 초기값으로 나타남
x = torch.empty(5,3)
print(x)

tensor([[9.1447e-36, 0.0000e+00, 3.3631e-44],
        [0.0000e+00,        nan, 0.0000e+00],
        [1.1578e+27, 1.1362e+30, 7.1547e+22],
        [4.5828e+30, 1.2121e+04, 7.1846e+22],
        [9.2198e-39, 7.0374e+22, 2.9483e-36]])


In [3]:
# 무작위로 초기화된 행렬 생성
x = torch.rand(5,3)
print(x)

tensor([[0.2534, 0.4466, 0.4802],
        [0.8169, 0.5713, 0.4459],
        [0.2865, 0.8560, 0.3783],
        [0.8858, 0.6335, 0.8205],
        [0.2922, 0.6933, 0.8965]])


In [4]:
x = torch.zeros(5, 3, dtype = torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [5]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [6]:
x = x.new_ones(5, 3, dtype = torch.double)
print(x)

x = torch.randn_like(x, dtype = torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.8408,  1.0596,  1.4416],
        [-0.4618,  0.3348, -0.3927],
        [-0.5196, -0.6476, -0.8847],
        [-0.0319, -1.0837,  1.4343],
        [-0.5981,  0.2077, -0.3680]])


In [7]:
# torch.Size 는 튜플타입으로 모든 튜플 연산을 지원
print(x.size())

torch.Size([5, 3])


In [8]:
# add methods
y = torch.rand(5, 3)
#1 grammer1
print(x + y)
#2 grammer2
print(torch.add(x,y))

tensor([[ 1.2267,  1.9357,  1.9597],
        [-0.0364,  1.1679, -0.3059],
        [-0.1863,  0.1957, -0.4719],
        [ 0.0938, -0.1054,  1.9403],
        [-0.1582,  0.5805, -0.2792]])
tensor([[ 1.2267,  1.9357,  1.9597],
        [-0.0364,  1.1679, -0.3059],
        [-0.1863,  0.1957, -0.4719],
        [ 0.0938, -0.1054,  1.9403],
        [-0.1582,  0.5805, -0.2792]])


In [9]:
#3 give tensor factor
result = torch.empty(5, 3)
torch.add(x, y, out = result)
print(result)

#4 in-place (all in-place things have _)
y.add_(x)
print(y)

tensor([[ 1.2267,  1.9357,  1.9597],
        [-0.0364,  1.1679, -0.3059],
        [-0.1863,  0.1957, -0.4719],
        [ 0.0938, -0.1054,  1.9403],
        [-0.1582,  0.5805, -0.2792]])
tensor([[ 1.2267,  1.9357,  1.9597],
        [-0.0364,  1.1679, -0.3059],
        [-0.1863,  0.1957, -0.4719],
        [ 0.0938, -0.1054,  1.9403],
        [-0.1582,  0.5805, -0.2792]])


In [10]:
print(x)
print(x[:, 1])

tensor([[ 0.8408,  1.0596,  1.4416],
        [-0.4618,  0.3348, -0.3927],
        [-0.5196, -0.6476, -0.8847],
        [-0.0319, -1.0837,  1.4343],
        [-0.5981,  0.2077, -0.3680]])
tensor([ 1.0596,  0.3348, -0.6476, -1.0837,  0.2077])


In [11]:
# 크기, 모양변경 .view
x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1, 8) # -1은 다른 차원에서 유추함
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [12]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.5720])
-0.572015643119812


In [13]:
# Numpy 변환(Bridge)
#(Torch Tensor가 CPU 상에 있다면) Torch Tensor와 NumPy 배열은 메모리 공간을 공유하기 때문에, 하나를 변경하면 다른 하나도 변경됩니다.

a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [14]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [15]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [16]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out = a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [17]:
# .to method 를 이용해서 장치변경 가능
if torch.cuda.is_available():
  device = torch.device("cuda")
  y = torch.ones_like(x, device = device)
  x = x.to(device)
  z = x + y
  print(z)
  print(z.to("cpu", torch.double)) #``.to`` 는 dtype도 함께 변경

tensor([0.4280], device='cuda:0')
tensor([0.4280], dtype=torch.float64)


In [18]:
# autograd

# requires_grad 는 해당 텐서의 모든 연산을 트랙킹함
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [19]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [20]:
print(y.grad_fn)

In [21]:
z = y * y * 3 
out = z.mean()
print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [22]:
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
True


In [23]:
#out 은 하나의 스칼라 값만 갖고 있기 때문에, out.backward() 는 out.backward(torch.tensor(1.)) 과 동일합니다.

out.backward()
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [24]:
x = torch.randn(3, requires_grad = True)
y = x * 2
while y.data.norm() < 1000:
  y = y * 2

print(y)

tensor([ 183.6982, 1559.0713,  484.9363], grad_fn=<MulBackward0>)


In [25]:
v = torch.tensor([0.1, 1.0, 0.0001], dtype = torch.float)
y.backward(v)

print(x.grad)

tensor([1.0240e+02, 1.0240e+03, 1.0240e-01])


In [26]:
print(x.requires_grad)
print((x ** 2).requires_grad)

with torch.no_grad():
  print((x ** 2).requires_grad)

True
True
False


In [27]:
print(x.requires_grad)
y = x.detach()
print(y.requires_grad)
print(x.eq(y).all())

True
False
tensor(True)


In [28]:
import torch
import torch.nn as nn
import torch.nn.functional as F

class Net(nn.Module):

  def __init__(self):
    super(Net, self).__init__()
    # 1 input image channel, 6 output channels, 3*3 square convolution kernel
    self.conv1 = nn.Conv2d(1, 6, 3)
    self.conv2 = nn.Conv2d(6, 16, 3)
    # an affine operation : y = Wx + b
    self.fc1 = nn.Linear(16 * 6 * 6, 120)
    self.fc2 = nn.Linear(120, 84)
    self.fc3 = nn.Linear(84, 10)

  def forward(self, x):
    # Max pooling over a (2, 2) window
    x = F.max_pool2d(F.relu(self.conv1(x)),(2, 2))
    # If the size is a square you can only specify a single number
    x = F.max_pool2d(F.relu(self.conv2(x)), 2)
    x = x.view(-1, self.num_flat_features(x))
    x = F.relu(self.fc1(x))
    x = F.relu(self.fc2(x))
    x = self.fc3(x)
    return x

  #Flatten
  def num_flat_features(self, x):
    size = x.size()[1:] # all dimensions except the batch dimension
    num_features = 1
    for s in size:
      num_features *= s
    return num_features
  
net = Net()
print(net)



Net(
  (conv1): Conv2d(1, 6, kernel_size=(3, 3), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(3, 3), stride=(1, 1))
  (fc1): Linear(in_features=576, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc3): Linear(in_features=84, out_features=10, bias=True)
)


In [29]:
params = list(net.parameters())
print(len(params))
print(params[0].size())

10
torch.Size([6, 1, 3, 3])


In [30]:
#LeNet

input = torch.randn(1, 1, 32, 32)
out = net(input)
#print(out)

net.zero_grad()
out.backward(torch.randn(1,10))

In [31]:
output = net(input)
target = torch.randn(10)
target = target.view(1, -1)
criterion = nn.MSELoss()

loss = criterion(output, target)
print(loss)

tensor(0.7324, grad_fn=<MseLossBackward>)


In [32]:
print(loss.grad_fn)
print(loss.grad_fn.next_functions[0][0]) #Linear
print(loss.grad_fn.next_functions[0][0].next_functions[0][0]) #ReLU

In [33]:
net.zero_grad() # zeroes the gradient buffers of all parameters

print('conv1.bias.grad before backward')
print(net.conv1.bias.grad)

loss.backward()

print('conv1.bias.grad before backward')
print(net.conv1.bias.grad)

conv1.bias.grad before backward
tensor([0., 0., 0., 0., 0., 0.])
conv1.bias.grad before backward
tensor([ 0.0077, -0.0072,  0.0021, -0.0035, -0.0090,  0.0030])


In [34]:
learning_rate = 0.01
for f in net.parameters():
  f.data.sub_(f.grad.data * learning_rate)
  print(f.data.size())

torch.Size([6, 1, 3, 3])
torch.Size([6])
torch.Size([16, 6, 3, 3])
torch.Size([16])
torch.Size([120, 576])
torch.Size([120])
torch.Size([84, 120])
torch.Size([84])
torch.Size([10, 84])
torch.Size([10])


In [35]:
import torch.optim as optim

# Generate Optimizer
optimizer = optim.SGD(net.parameters(), lr = 0.01)

# training loop
optimizer.zero_grad()
output = net(input)
loss = criterion(output, target)
loss.backward()
optimizer.step()