<a href="https://colab.research.google.com/github/data-prom/Kaggle_daily_commit/blob/master/torch_tutorial/Playground.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# 파이썬 2에서 파이썬 3로 넘어갈 수 있게끔 도와주는 라이브러리 __future__
from __future__ import print_function
import torch

In [ ]:
# 초기화되지 않은 행렬 생성되면 할당된 메모리에 존재하던 값이 초기값으로 나타남
x = torch.empty(5,3)
print(x)

tensor([[3.6319e-36, 0.0000e+00, 3.3631e-44],
        [0.0000e+00,        nan, 0.0000e+00],
        [1.1578e+27, 1.1362e+30, 7.1547e+22],
        [4.5828e+30, 1.2121e+04, 7.1846e+22],
        [9.2198e-39, 7.0374e+22, 1.3375e-36]])


In [ ]:
# 무작위로 초기화된 행렬 생성
x = torch.rand(5,3)
print(x)

tensor([[0.6448, 0.8435, 0.2802],
        [0.4894, 0.0036, 0.6586],
        [0.9317, 0.4097, 0.6833],
        [0.3595, 0.1921, 0.5750],
        [0.5603, 0.8199, 0.2885]])


In [ ]:
x = torch.zeros(5, 3, dtype = torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [ ]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [ ]:
x = x.new_ones(5, 3, dtype = torch.double)
print(x)

x = torch.randn_like(x, dtype = torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.3728, -0.2505,  1.2367],
        [ 1.3862,  0.2224,  0.2928],
        [-0.5003, -1.3948,  1.6461],
        [-0.7736, -0.7432,  2.3070],
        [-0.9794,  1.5073,  0.6355]])


In [ ]:
# torch.Size 는 튜플타입으로 모든 튜플 연산을 지원
print(x.size())

torch.Size([5, 3])


In [ ]:
# add methods
y = torch.rand(5, 3)
#1 grammer1
print(x + y)
#2 grammer2
print(torch.add(x,y))

tensor([[-0.0370,  0.3046,  2.0481],
        [ 2.0285,  0.6705,  0.5031],
        [ 0.0325, -0.9571,  2.2205],
        [-0.6745, -0.6702,  2.4165],
        [-0.7836,  2.3822,  1.0505]])
tensor([[-0.0370,  0.3046,  2.0481],
        [ 2.0285,  0.6705,  0.5031],
        [ 0.0325, -0.9571,  2.2205],
        [-0.6745, -0.6702,  2.4165],
        [-0.7836,  2.3822,  1.0505]])


In [ ]:
#3 give tensor factor
result = torch.empty(5, 3)
torch.add(x, y, out = result)
print(result)

#4 in-place (all in-place things have _)
y.add_(x)
print(y)

tensor([[-0.0370,  0.3046,  2.0481],
        [ 2.0285,  0.6705,  0.5031],
        [ 0.0325, -0.9571,  2.2205],
        [-0.6745, -0.6702,  2.4165],
        [-0.7836,  2.3822,  1.0505]])
tensor([[-0.0370,  0.3046,  2.0481],
        [ 2.0285,  0.6705,  0.5031],
        [ 0.0325, -0.9571,  2.2205],
        [-0.6745, -0.6702,  2.4165],
        [-0.7836,  2.3822,  1.0505]])


In [ ]:
print(x)
print(x[:, 1])

tensor([[-0.3728, -0.2505,  1.2367],
        [ 1.3862,  0.2224,  0.2928],
        [-0.5003, -1.3948,  1.6461],
        [-0.7736, -0.7432,  2.3070],
        [-0.9794,  1.5073,  0.6355]])
tensor([-0.2505,  0.2224, -1.3948, -0.7432,  1.5073])


In [ ]:
# 크기, 모양변경 .view
x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1, 8) # -1은 다른 차원에서 유추함
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [ ]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.8546])
0.8545680046081543


In [ ]:
# Numpy 변환(Bridge)
#(Torch Tensor가 CPU 상에 있다면) Torch Tensor와 NumPy 배열은 메모리 공간을 공유하기 때문에, 하나를 변경하면 다른 하나도 변경됩니다.

a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [ ]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [ ]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [ ]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out = a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [ ]:
# .to method 를 이용해서 장치변경 가능
if torch.cuda.is_available():
  device = torch.device("cuda")
  y = torch.ones_like(x, device = device)
  x = x.to(device)
  z = x + y
  print(z)
  print(z.to("cpu", torch.double)) #``.to`` 는 dtype도 함께 변경

tensor([1.8546], device='cuda:0')
tensor([1.8546], dtype=torch.float64)


In [ ]:
# autograd

# requires_grad 는 해당 텐서의 모든 연산을 트랙킹함
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [ ]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [ ]:
print(y.grad_fn)

In [ ]:
z = y * y * 3 
out = z.mean()
print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [ ]:
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
True


In [ ]:
#out 은 하나의 스칼라 값만 갖고 있기 때문에, out.backward() 는 out.backward(torch.tensor(1.)) 과 동일합니다.

out.backward()
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [ ]:
x = torch.randn(3, requires_grad = True)
y = x * 2
while y.data.norm() < 1000:
  y = y * 2

print(y)

tensor([  30.0301,   -5.2217, 1124.1178], grad_fn=<MulBackward0>)


In [ ]:
v = torch.tensor([0.1, 1.0, 0.0001], dtype = torch.float)
y.backward(v)

print(x.grad)

RuntimeError: ignored

In [ ]:
print(x.requires_grad)
print((x ** 2).requires_grad)

with torch.no_grad():
  print((x ** 2).requires_grad)

True
True
False


In [ ]:
print(x.requires_grad)
y = x.detach()
print(y.requires_grad)
print(x.eq(y).all())

True
False
tensor(True)


In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F

class Net(nn.Module):

  def __init__(self):
    super(Net, self).__init__()
    # 1 input image channel, 6 output channels, 3*3 square convolution kernel
    self.conv1 = nn.Conv2d(1, 6, 3)
    self.conv2 = nn.Conv2d(6, 16, 3)
    # an affine operation : y = Wx + b
    self.fc1 = nn.Linear(16 * 6 * 6, 120)
    self.fc2 = nn.Linear(120, 84)
    self.fc3 = nn.Linear(84, 10)

  def forward(self, x):
    # Max pooling over a (2, 2) window
    x = F.max_pool2d(F.relu(self.conv1(x)),(2, 2))
    # If the size is a square you can only specify a single number
    x = F.max_pool2d(F.relu(self.conv2(x)), 2)
    x = F.view(-1, self.num_flat_features(x))
    x = F.relu(self.fc1(x))
    x = F.relu(self.fc2(x))
    x = self.fc3(x)
    return x

  def num_flat_features(self, x):
    size = x.size()[1:] # all dimensions except the batch dimension
    num_features = 1
    for s in size:
      num_features *= s
    return num_features
  
net = Net()
print(net)



Net(
  (conv1): Conv2d(1, 6, kernel_size=(3, 3), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(3, 3), stride=(1, 1))
  (fc1): Linear(in_features=576, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc3): Linear(in_features=84, out_features=10, bias=True)
)
